package extension

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/shutu-ai/shutu-agent/sdk/extension"
	"github.com/shutu-ai/shutu-knowledge/internal/app"
	"github.com/shutu-ai/shutu-knowledge/internal/knowledge"
	"github.com/shutu-ai/shutu-knowledge/internal/operations"
)

func testApp(t *testing.T) *app.App {
	t.Helper()
	t.Setenv("SHUTU_KNOWLEDGE_HOME", t.TempDir())
	t.Setenv("SHUTU_KNOWLEDGE_DISABLE_MANAGED_RUNTIME", "1")
	application, err := app.New(context.Background())
	if err != nil {
		t.Fatalf("app: %v", err)
	}
	t.Cleanup(application.Close)
	return application
}

func TestManifestValidatesAgainstSDK(t *testing.T) {
	if err := Manifest().Validate(); err != nil {
		t.Fatalf("manifest invalid: %v", err)
	}
	manifest := Manifest()
	wantTools := []string{
		"knowledge_search", "knowledge_list_bases", "knowledge_create_base",
		"knowledge_delete_base", "knowledge_add_document", "knowledge_list_documents",
		"knowledge_delete_document", "knowledge_import_url", "knowledge_refresh_url",
		"knowledge_stats", "knowledge_get_document", "knowledge_read_document",
		"knowledge_reindex_document", "knowledge_reindex_base",
		"knowledge_maintenance_storage",
		"knowledge_operation_status", "knowledge_operation_cancel",
		"knowledge_operation_retry",
	}
	gotTools := make([]string, 0, len(manifest.Tools.Definitions))
	for _, definition := range manifest.Tools.Definitions {
		gotTools = append(gotTools, definition.Name)
	}
	if !reflect.DeepEqual(gotTools, wantTools) {
		t.Fatalf("tool inventory: got %v want %v", gotTools, wantTools)
	}
	if !manifest.Capabilities.ContextProvider || manifest.ContextProvider.Strategy != extension.ContextOnUserInputChange {
		t.Fatalf("context provider: %+v", manifest.ContextProvider)
	}
	if manifest.Events.Subscribe != nil {
		t.Fatalf("event subscriptions should be empty: %+v", manifest.Events.Subscribe)
	}
	if len(manifest.Permissions) != 3 {
		t.Fatalf("permissions: %+v", manifest.Permissions)
	}
	for _, definition := range manifest.Tools.Definitions {
		switch definition.Name {
		case "knowledge_delete_base", "knowledge_delete_document", "knowledge_maintenance_storage":
			if definition.Risk != extension.ToolRiskDestructive || !definition.RequiresApproval {
				t.Fatalf("%s risk: %+v", definition.Name, definition)
			}
		case "knowledge_search", "knowledge_list_bases", "knowledge_get_document", "knowledge_read_document":
			if definition.Risk != extension.ToolRiskRead || definition.RequiresApproval {
				t.Fatalf("%s risk: %+v", definition.Name, definition)
			}
		}
	}
}

func TestMaintenanceStorageToolQuarantinesOrphans(t *testing.T) {
	application := testApp(t)
	base, err := application.Knowledge.CreateBase("Maintenance", "", "", knowledge.BaseConfig{})
	if err != nil {
		t.Fatal(err)
	}
	orphan := filepath.Join(application.RawStore.Root(), base.ID, "orphan.bin")
	if err := os.MkdirAll(filepath.Dir(orphan), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(orphan, []byte("bytes"), 0o600); err != nil {
		t.Fatal(err)
	}
	result, err := CallTool(context.Background(), application, extension.ToolCallRequest{
		Name: "knowledge_maintenance_storage",
	})
	if err != nil || result.Error != "" {
		t.Fatalf("submit maintenance: %v %s", err, result.Error)
	}
	submitted := result.Value.(map[string]any)
	operationID, _ := submitted["operationId"].(string)
	if operationID == "" {
		t.Fatalf("maintenance submission: %#v", submitted)
	}
	operation := waitForOperation(t, application, operationID)
	if operation.State != operations.StateSucceeded {
		t.Fatalf("maintenance operation: %#v", operation)
	}
	var maintenanceResult struct {
		Quarantined     int   `json:"quarantined"`
		QuarantineBytes int64 `json:"quarantineBytes"`
	}
	if err := json.Unmarshal(operation.Result, &maintenanceResult); err != nil {
		t.Fatal(err)
	}
	if maintenanceResult.Quarantined != 1 || maintenanceResult.QuarantineBytes != 5 {
		t.Fatalf("maintenance result: %+v", maintenanceResult)
	}
	if _, err := os.Stat(orphan); !os.IsNotExist(err) {
		t.Fatalf("orphan remained active: %v", err)
	}
}

func TestDeployedManifestValidates(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "extension.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := extension.ParseManifest(data)
	if err != nil {
		t.Fatalf("parse deployed manifest: %v", err)
	}
	if manifest.ID != ExtensionID || !manifest.Capabilities.Tools || !manifest.Capabilities.ContextProvider {
		t.Fatalf("deployed manifest: %+v", manifest)
	}
	if manifest.ContextProvider.Strategy != extension.ContextOnUserInputChange {
		t.Fatalf("context strategy: %+v", manifest.ContextProvider)
	}
	if len(manifest.Tools.Definitions) != 0 {
		t.Fatalf("tool definitions should be generated by initialize to avoid drift: %d", len(manifest.Tools.Definitions))
	}
}

// TestStdioHandshakeAndHealth drives the real JSON-RPC loop end to end:
// initialize (version negotiation) then health (DB-backed readiness).
func TestStdioHandshakeAndHealth(t *testing.T) {
	application := testApp(t)

	requests := strings.Join([]string{
		`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"shutu-extension/1","agentApiVersion":"1.0","agentName":"shutu-agent","supportedCapabilities":{"health":true,"lifecycle":true}}}`,
		`{"jsonrpc":"2.0","id":2,"method":"health"}`,
		`{"jsonrpc":"2.0","id":3,"method":"shutdown"}`,
	}, "\n") + "\n"

	var out bytes.Buffer
	if err := Run(context.Background(), application, strings.NewReader(requests), &out); err != nil {
		t.Fatalf("run: %v", err)
	}
	response := out.String()
	for _, want := range []string{`"protocolVersion":"shutu-extension/1"`, `"ready":true`, `"status":"ready"`} {
		if !strings.Contains(response, want) {
			t.Fatalf("response missing %s:\n%s", want, response)
		}
	}
}

func TestExtensionWebContributionServesAPI(t *testing.T) {
	application := testApp(t)
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	inReader, inWriter := io.Pipe()
	outReader, outWriter := io.Pipe()
	done := make(chan error, 1)
	go func() { done <- Run(ctx, application, inReader, outWriter) }()

	initialize := `{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"shutu-extension/1","agentApiVersion":"1.0","agentName":"shutu-agent","supportedCapabilities":{"tools":true,"contextProvider":true,"web":true,"health":true,"lifecycle":true}}}` + "\n"
	if _, err := inWriter.Write([]byte(initialize)); err != nil {
		t.Fatal(err)
	}
	line, err := bufio.NewReader(outReader).ReadString('\n')
	if err != nil {
		t.Fatal(err)
	}
	var message struct {
		Result struct {
			WebBaseURL string `json:"webBaseUrl"`
		} `json:"result"`
	}
	if err := json.Unmarshal([]byte(line), &message); err != nil {
		t.Fatal(err)
	}
	webURL := message.Result.WebBaseURL
	if !strings.HasPrefix(webURL, "http://127.0.0.1:") {
		t.Fatalf("extension web URL: %q", webURL)
	}
	httpResponse, err := http.Get(webURL + "/api/status")
	if err != nil {
		t.Fatal(err)
	}
	_ = httpResponse.Body.Close()
	if httpResponse.StatusCode != http.StatusOK {
		t.Fatalf("extension web status: %d", httpResponse.StatusCode)
	}
	if err := inWriter.Close(); err != nil {
		t.Fatal(err)
	}
	if err := <-done; err != nil {
		t.Fatalf("extension run: %v", err)
	}
}

func TestToolLifecycleAndContext(t *testing.T) {
	application := testApp(t)
	ctx := context.Background()

	base, err := application.Knowledge.CreateBase("Project", "", "", knowledge.BaseConfig{})
	if err != nil {
		t.Fatal(err)
	}
	result, err := CallTool(ctx, application, extension.ToolCallRequest{
		Name:      "knowledge_add_document",
		Arguments: map[string]any{"baseId": base.ID, "title": "Operations", "content": "Retry budget retry budget retry budget. The deployment token is alpha-7788 and the retry budget is 30 seconds."},
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.Error != "" {
		t.Fatalf("add document: %s", result.Error)
	}
	submitted := result.Value.(map[string]any)
	operationID, _ := submitted["operationId"].(string)
	if operationID == "" {
		t.Fatalf("add document submission: %#v", submitted)
	}
	operation := waitForOperation(t, application, operationID)
	if operation.State != operations.StateSucceeded {
		t.Fatalf("add document operation: %#v", operation)
	}
	var documentResult map[string]any
	if err := json.Unmarshal(operation.Result, &documentResult); err != nil {
		t.Fatal(err)
	}
	documents, _ := documentResult["documents"].([]any)
	if len(documents) != 1 {
		t.Fatalf("add document result: %#v", documentResult)
	}
	document, _ := documents[0].(map[string]any)
	if chunkCount, _ := document["chunkCount"].(float64); chunkCount < 1 {
		t.Fatalf("add document result: %#v", documentResult)
	}

	search, err := CallTool(ctx, application, extension.ToolCallRequest{
		Name:      "knowledge_search",
		Arguments: map[string]any{"query": "retry budget"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if search.Error != "" {
		t.Fatalf("search: %s", search.Error)
	}
	searchValue := search.Value.(searchToolResult)
	if searchValue.Total != 1 || len(searchValue.Citations) != 1 || !strings.Contains(searchValue.Citations[0], "Operations") {
		t.Fatalf("search result: %#v", searchValue)
	}

	provider, err := ProvideContext(ctx, application, extension.ContextRequest{
		SessionID: "session-1", TurnID: "turn-1", UserInput: "The retry budget is 30 seconds",
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(provider.Contributions) != 1 || !strings.Contains(provider.Contributions[0].Content, "retry budget") {
		t.Fatalf("context provider: %#v", provider)
	}
	if provider.Contributions[0].Metadata["docId"] == "" || provider.Contributions[0].EstimatedTokens <= 0 {
		t.Fatalf("context metadata: %#v", provider.Contributions[0])
	}

	list, err := CallTool(ctx, application, extension.ToolCallRequest{
		Name: "knowledge_list_documents", Arguments: map[string]any{"baseId": base.ID},
	})
	if err != nil {
		t.Fatal(err)
	}
	if list.Error != "" || !strings.Contains(list.Value.(map[string]any)["documents"].([]documentSummary)[0].ID, "") {
		t.Fatalf("list documents: %#v", list)
	}
	page, err := CallTool(ctx, application, extension.ToolCallRequest{
		Name: "knowledge_list_documents", Arguments: map[string]any{"baseId": base.ID, "limit": 1, "offset": 1},
	})
	if err != nil {
		t.Fatal(err)
	}
	pageValue := page.Value.(map[string]any)
	if page.Error != "" || len(pageValue["documents"].([]documentSummary)) > 1 || pageValue["limit"].(int) != 1 || pageValue["offset"].(int) != 1 {
		t.Fatalf("bounded list documents: %#v", page)
	}
	outline, err := CallTool(ctx, application, extension.ToolCallRequest{
		Name: "knowledge_list_bases", Arguments: map[string]any{"baseId": base.ID, "limit": 1, "offset": 0},
	})
	if err != nil {
		t.Fatal(err)
	}
	outlineValue := outline.Value.(map[string]any)
	if outline.Error != "" || len(outlineValue["documents"].([]documentSummary)) != 1 || outlineValue["limit"].(int) != 1 {
		t.Fatalf("bounded base outline: %#v", outline)
	}

	emptyScope := []string{}
	if err := application.Knowledge.SetEnabledScope(boolPointer(true), &emptyScope); err != nil {
		t.Fatal(err)
	}
	emptyList, err := CallTool(ctx, application, extension.ToolCallRequest{Name: "knowledge_list_bases"})
	if err != nil || emptyList.Error != "" || len(emptyList.Value.(map[string]any)["bases"].([]baseSummary)) != 0 {
		t.Fatalf("explicit empty scope list bases: %#v %#v", emptyList, err)
	}
	emptyDenied, err := CallTool(ctx, application, extension.ToolCallRequest{
		Name: "knowledge_list_documents", Arguments: map[string]any{"baseId": base.ID},
	})
	if err != nil || emptyDenied.Error == "" {
		t.Fatalf("explicit empty scope denied: %#v %#v", emptyDenied, err)
	}

	if err := application.Knowledge.SetEnabledScope(boolPointer(false), nil); err != nil {
		t.Fatal(err)
	}
	disabled, err := CallTool(ctx, application, extension.ToolCallRequest{
		Name: "knowledge_list_documents", Arguments: map[string]any{"baseId": base.ID},
	})
	if err != nil || disabled.Error == "" {
		t.Fatalf("disabled scope: %#v %#v", disabled, err)
	}
}

type gatedAgentEmbedder struct {
	started chan struct{}
	release chan struct{}
}

func (e *gatedAgentEmbedder) Embed(_ context.Context, texts []string) ([][]float64, error) {
	close(e.started)
	<-e.release
	out := make([][]float64, 0, len(texts))
	for range texts {
		out = append(out, []float64{1, 0})
	}
	return out, nil
}

func (e *gatedAgentEmbedder) ModelKey() string { return "fake:gated-agent" }

func TestOperationCancelToolCancelsRunningImport(t *testing.T) {
	application := testApp(t)
	ctx := context.Background()
	base, err := application.Knowledge.CreateBase("Agent Cancel", "", "", knowledge.BaseConfig{})
	if err != nil {
		t.Fatal(err)
	}
	application.Config.Embedding.Provider = "openai"
	application.Knowledge.SetGlobalConfig(application.Config)
	blocked := &gatedAgentEmbedder{started: make(chan struct{}), release: make(chan struct{})}
	application.Knowledge.SetProviders(blocked, nil)

	submittedCall, err := CallTool(ctx, application, extension.ToolCallRequest{
		Name: "knowledge_add_document",
		Arguments: map[string]any{
			"baseId": base.ID, "title": "Cancellable", "content": "# Storage\n\nwait for Agent cancellation",
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	if submittedCall.Error != "" {
		t.Fatalf("submit through Agent tool: %s", submittedCall.Error)
	}
	submitted := submittedCall.Value.(map[string]any)
	operationID, _ := submitted["operationId"].(string)
	if operationID == "" {
		t.Fatalf("Agent submission omitted operationId: %#v", submitted)
	}
	select {
	case <-blocked.started:
	case <-time.After(2 * time.Second):
		t.Fatal("Agent-submitted import did not reach cancellable embedding phase")
	}

	cancelCall, err := CallTool(ctx, application, extension.ToolCallRequest{
		Name:      "knowledge_operation_cancel",
		Arguments: map[string]any{"operationId": operationID},
	})
	if err != nil {
		t.Fatal(err)
	}
	if cancelCall.Error != "" {
		t.Fatalf("cancel through Agent tool: %s", cancelCall.Error)
	}
	cancelling := cancelCall.Value.(operations.Operation)
	if cancelling.State != operations.StateCancelling || !cancelling.CancelRequested {
		t.Fatalf("Agent cancel response: %#v", cancelling)
	}
	close(blocked.release)

	deadline := time.Now().Add(5 * time.Second)
	for {
		statusCall, err := CallTool(ctx, application, extension.ToolCallRequest{
			Name:      "knowledge_operation_status",
			Arguments: map[string]any{"operationId": operationID},
		})
		if err != nil {
			t.Fatal(err)
		}
		if statusCall.Error != "" {
			t.Fatalf("status after Agent cancel: %s", statusCall.Error)
		}
		operation := statusCall.Value.(operations.Operation)
		if operation.State == operations.StateCancelled {
			break
		}
		if operation.State == operations.StateSucceeded || operation.State == operations.StateFailed {
			t.Fatalf("Agent cancel converged to %s: %#v", operation.State, operation)
		}
		if time.Now().After(deadline) {
			t.Fatalf("operation state = %s", operation.State)
		}
		time.Sleep(20 * time.Millisecond)
	}
}

func waitForOperation(t *testing.T, application *app.App, operationID string) operations.Operation {
	t.Helper()
	deadline := time.Now().Add(15 * time.Second)
	for {
		result, err := CallTool(context.Background(), application, extension.ToolCallRequest{
			Name:      "knowledge_operation_status",
			Arguments: map[string]any{"operationId": operationID},
		})
		if err != nil {
			t.Fatal(err)
		}
		if result.Error != "" {
			t.Fatalf("operation status: %s", result.Error)
		}
		operation := result.Value.(operations.Operation)
		switch operation.State {
		case operations.StateSucceeded, operations.StateFailed, operations.StateCancelled:
			return operation
		}
		if time.Now().After(deadline) {
			t.Fatalf("operation %s did not finish: %#v", operationID, operation)
		}
		time.Sleep(20 * time.Millisecond)
	}
}

func boolPointer(value bool) *bool { return &value }

func TestAgentSDKImportLayering(t *testing.T) {
	root := ".."
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		if filepath.Ext(path) != ".go" || filepath.Base(filepath.Dir(path)) == "extension" {
			return nil
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		if strings.Contains(string(data), "github.com/shutu-ai/shutu-agent/sdk/extension") {
			t.Fatalf("Agent SDK import outside extension adapter: %s", path)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}
